image: nikolaik/python-nodejs:latest
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
#AWS access keys stored as secret variables 
variables:
  AWS_ACCESS_KEY_ID: $ACCESS_KEY_ID 
  AWS_SECRET_ACCESS_KEY: $SECRET_ACCESS_KEY
#This declares the pipeline stages  
stages:
  - install
  - test
  - deploy
cache:
  paths:
  - node_modules/
prodInstall:
  stage: install
  script:
    - npm install
  artifacts:
    untracked: true
unitTesting:
  stage: test
  dependencies:
    - prodInstall
  script:
    - npm install
    - npm run build
    - npm test
  artifacts:
    untracked: true
deployingProd:
  stage: deploy
  only:
    - master
  dependencies:
    - prodInstall
    - unitTesting
  script:
    - npm install
    - npm run build
    - pip3 install awscli
    - aws configure set profile bucket-prod
    - aws configure set aws_access_key_id "$ACCESS_KEY_ID"
    - aws configure set aws_secret_access_key "$SECRET_ACCESS_KEY"
    - aws s3 sync ./build/ s3://rapicgitlabdev